sudo: false

language: rust
rust:
    - stable
    - beta
    - nightly

after_success: 
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --no-verify --token ${CRATESIO_TOKEN}
